language: python

install:
  - make --version && python --version
  - cd tests/gen_makefile && ../../bin/gen_makefile config.json > Makefile
  - cd test_dep1 && ../../../bin/gen_makefile config.json > Makefile
  - cd ../test_dep2 && ../../../bin/gen_makefile config.json > Makefile
  - cd test_dep3 && ../../../../bin/gen_makefile config.json > Makefile
  - cd "$TRAVIS_BUILD_DIR"/tests/gen_makefile
  - make all
  - make re
  - make depre
  - make clean
  - make fclean
  - make depfclean
  - make regen
  - make depre

script:
  - bin/test_core
  - test_dep1/bin/test_dep1
  - test_dep2/bin/test_dep2
  - test_dep2/test_dep3/bin/test_dep3